### PR TITLE
Porting of AWSCore, AWSCognito, AWSLambda and AWSS3 to tvOS, watchOS and macOS

### PR DESCRIPTION
**Pull request by ifullgaz**
Porting of AWSCore, AWSCognito, AWSLambda and AWSS3 to tvOS, watchOS and macOS.
The resulting code and frameworks can be used to write applications that use Cognito, Lambda and S3 on the 4 Apple platforms: iOS, tvOS, watchOS and macOS.

### CODE REVIEW

**Comment by karthiksaligrama** [comment]
Thanks for the PR. I'll take a look at it and respond

**Comment by santoshkumar918** [comment]
Any updates regarding AWS Frameworks for Watch OS.

**Comment by sanathyml** [comment]
@karthiksaligrama When can we expect AWS Framework for watch OS.

**Comment by kvasukib** [comment]
Hi @ifullgaz, Can you rebase your branch, resolve your conflicts and re-submit the PR?

**Comment by Abeansits** [comment]
Any news on this?

**Comment by vccabral** [comment]
I rebased this branch on top of master (2.6.18) and pod installed from my fork and no luck. 
https://github.com/NewTouchDigital/aws-sdk-ios/tree/sdk_iwatch

I would love to seem some renewed effort around this issue. Is there a contributor guide to help someone get started on a port of the sdk to iwatch?

**Comment by vccabral** [comment]
@kvasukib @karthiksaligrama 

After rebase, I tried a few things. I updates the podspec files to include watchos and finally moved past the error warning when installing from my fork. At it's current state, the code cannot build because of a SystemConfiguration library that seems to not be on the watch if i understand the error logs correctly.

Ld /Users/osxuser/Library/Developer/Xcode/DerivedData/WatchAppName-fvzfbpyutkcifkaajtsobldxanrc/Build/Products/Debug-watchos/AWSCore-watchOS/AWSCore.framework/AWSCore normal armv7k
    cd "/Users/osxuser/Documents/code/NTDI_Corporate/iwatch apps/WatchAppName/Pods"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    export WATCHOS_DEPLOYMENT_TARGET=4.3
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch armv7k -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/WatchOS.platform/Developer/SDKs/WatchOS4.3.sdk -L/Users/osxuser/Library/Developer/Xcode/DerivedData/WatchAppName-fvzfbpyutkcifkaajtsobldxanrc/Build/Products/Debug-watchos/AWSCore-watchOS -F/Users/osxuser/Library/Developer/Xcode/DerivedData/WatchAppName-fvzfbpyutkcifkaajtsobldxanrc/Build/Products/Debug-watchos/AWSCore-watchOS -filelist /Users/osxuser/Library/Developer/Xcode/DerivedData/WatchAppName-fvzfbpyutkcifkaajtsobldxanrc/Build/Intermediates.noindex/Pods.build/Debug-watchos/AWSCore-watchOS.build/Objects-normal/armv7k/AWSCore.LinkFileList -install_name @rpath/AWSCore.framework/AWSCore -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -mwatchos-version-min=4.3 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/osxuser/Library/Developer/Xcode/DerivedData/WatchAppName-fvzfbpyutkcifkaajtsobldxanrc/Build/Intermediates.noindex/Pods.build/Debug-watchos/AWSCore-watchOS.build/Objects-normal/armv7k/AWSCore_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -fembed-bitcode-marker -fobjc-arc -fobjc-link-runtime -fapplication-extension -lsqlite3 -lz -framework CoreGraphics -framework Foundation -framework Security -framework SystemConfiguration -framework UIKit -framework CoreGraphics -framework Foundation -framework Security -framework SystemConfiguration -framework UIKit -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /Users/osxuser/Library/Developer/Xcode/DerivedData/WatchAppName-fvzfbpyutkcifkaajtsobldxanrc/Build/Intermediates.noindex/Pods.build/Debug-watchos/AWSCore-watchOS.build/Objects-normal/armv7k/AWSCore_dependency_info.dat -o /Users/osxuser/Library/Developer/Xcode/DerivedData/WatchAppName-fvzfbpyutkcifkaajtsobldxanrc/Build/Products/Debug-watchos/AWSCore-watchOS/AWSCore.framework/AWSCore

ld: framework not found SystemConfiguration
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by vccabral** [comment]
I believe a few other services would be highly valuable on the watch including AWSKinesis for logging and moving streams off of the watches securely with wifi and cell data. It would also be nice for a shared auth system between the phone and watch for security. Meaning, I would like to make AWS calls with the same user that is authenticated on the phone.

**Comment by muellerfr** [comment]
Hello @ifullgaz,

I have added this as a feature request in our backlog and have submitted it to the team for prioritization. I do not have specific timeline that I can share at this point. We will let you know, either on this thread, or through a forum announcement when the feature is released in the SDK.

**Comment by vccabral** [comment]
@muellerfr I have a direct need for this feature. Unfortunately I am having trouble even compiling the source with XCode 10.1 beta. See this question on [SO for reference.](https://stackoverflow.com/questions/53053405/how-to-build-awsiossdkv2). I noticed the[ blog article](https://aws.amazon.com/blogs/mobile/building-the-aws-sdk-for-ios-from-source/) on building version 1 of the SDK which seems out of date.   Do you all have up to date guidance?

**Comment by muellerfr** [comment]
@vccabral, which platform are you trying to target?

**Comment by vccabral** [comment]
@muellerfr watchos5

**Comment by vccabral** [comment]
@muellerfr I am going to post a bounty on solving this problem on bountysource.com, can you all open the issue to allow that to go in effect. For some reason(maybe an obvious one), I can't open a bounty on a closed issue. 

https://www.bountysource.com/issues/42648312-porting-of-awscore-awscognito-awslambda-and-awss3-to-tvos-watchos-and-macos

**Comment by vccabral** [comment]
@muellerfr ok thanks for the update. I have a fork and I am attempting to integrate the changes @ifullgaz . I have run into several road blocks (duplicate file creation, missing configuration.json, facebookid from cognitio tests). Do you have contribution guidelines or a getting started? I assume your team has deep knowledge of exactly how to take this project from clone to full regression testing to enable more effective source management but I have not seen any documentation on the subject aside from a blog post about the version 1 of the SDK. I appreciate the great API!

**Pull request closed without merging**
