### PR TITLE
Add AWSS3TransferUtilityUploadTask

### PR DESCRIPTION
**Pull request by 1amageek**
AWSS3TransferUtilityUploadTask can read that.
@property (readonly) int64_t countOfBytesSent;
@property (readonly) int64_t countOfBytesExpectedToSend;

### CODE REVIEW

**Comment by 1amageek** [comment]
thank you for reply.

I want to manage all of the progress in the parent progress.
Now, because I do not have access to NSURLUploadSession, are as follows.

``` objective-c

self.uploadProgress = ^(AWSS3TransferUtilityTask *task, int64_t bytesSent, int64_t totalBytesSent, int64_t totalBytesExpectedToSend) {

            NSString *key = [NSString stringWithFormat:@"%lu", (unsigned long)task.taskIdentifier];
            if (![__self.allProgress.allKeys containsObject:key]) {
                NSProgress *progress = [NSProgress progressWithTotalUnitCount:totalBytesExpectedToSend];
                int64_t totalUnitCount = __self.progress.totalUnitCount + totalBytesExpectedToSend;
                [__self.progress setTotalUnitCount:totalUnitCount];
                [__self.progress addChild:progress withPendingUnitCount:totalBytesExpectedToSend];
                [__self.allProgress setObject:progress forKey:key];
            }
        
            NSProgress *progress = [__self.allProgress objectForKey:key];
            [progress setCompletedUnitCount:totalBytesSent];

        };

``` 

And I want to the next by the improvement.

``` objective-c

AWSS3TransferUtility *transferUtility = [AWSS3TransferUtility defaultS3TransferUtility];
                            NSString *key = [NSString stringWithFormat:@"%@/%@", self.familyID, hash];
                            [[transferUtility uploadData:data
                                                  bucket:self.bucket
                                                     key:key
                                             contentType:@"image/jpeg"
                                              expression:expression
                                        completionHander:self.completionHandler] continueWithBlock:^id(AWSTask *task) {
                                if (task.error) {
                                    NSLog(@"Error: %@", task.error);
                                }
                                if (task.exception) {
                                    NSLog(@"Exception: %@", task.exception);
                                }
                                if (task.result) {
                                    NSLog(@"result %@", task.result);
                                }
                                
                                
                                AWSTaskCompletionSource *source = (AWSTaskCompletionSource *)[transferUtility getUploadTasks];
                                AWSS3TransferUtilityUploadTask *transferUtilityUploadTask = (AWSS3TransferUtilityUploadTask *)source.task;

                                NSLog(@"upload %@", source.task);
                                // Create progress 
                                
                                return nil;
                            }];
```

**Comment by 1amageek** [comment]
Do you know the MultipeerGroupChat? MultipeerGroupChat is a great sample code.

In the sample code MCSession is used.
Handling of NSProgress of MCSession is cool very simple.

``` objective-c

/*
   Send a resource referenced by an NSURL to a remote peer. The resource
   can be a file or an HTTP document. The completionHandler is called when
   the resource is received by the remote peer or if an error occurred.
   The remote peer will get a -session:didStartReceivingResourceWithName:
   fromPeer:withProgress callback when it starts receiving the resource and
   a -session:didFinishReceivingResourceWithName:fromPeer:atURL:withError:
   when the resource has been fully received.

   The primary mechanism for observing progress of the send should be to
   create an NSProgress using +progressWithTotalUnitCount,
   -becomeCurrentWithPendingUnitCount:, invoking this method, then calling
   -resignCurrent. This is described in the NSProgress documentation.
   Alternatively, if you wish to observe the progress directly instead
   of incorporating it into a larger operation, you may observe the
   NSProgress returned from this method.
 */
- (nullable NSProgress *)sendResourceAtURL:(NSURL *)resourceURL
                                  withName:(NSString *)resourceName
                                    toPeer:(MCPeerID *)peerID
                     withCompletionHandler:(nullable void (^)(NSError * __nullable error))completionHandler;

```

**Comment by yosuke-matsuda** [comment]
Sounds like you prefer the use of `NSProgress` as well. I'll put this in our requested feature list. Thanks.

**Comment by 1amageek** [comment]
:+1:

**Comment by yosuke-matsuda** [comment]
Sorry for taking long to update this. We've released the AWS Mobile SDK for iOS 2.4.1 with the `NSProgress` progress feedback block in `AWSS3TransferUtility`. Thanks.

**Pull request closed without merging**
