### PR TITLE
Fix AWSLex.podspec

### PR DESCRIPTION
**Pull request by yaakaito**

### CODE REVIEW

**Comment by minbi** [comment]
Can you explain why you have changed to double quotes?

**Comment by yaakaito** [comment]
'#{s.name}' is not expand in single quotes.

**Comment by minbi** [comment]
Thank you. We will merge this with the next release.

**Comment by minbi** [comment]
The entry here seems to not affect the operation of Bluefront in the project. We have chosen to simply remove the entire search path. Please re-open if there is an issue with this.

**Pull request closed without merging**
